server:
  port: 8008

logging:
  level:
    learning: trace

spring:
#  shardingsphere:
#    datasource:
#      names: data1
#      data1:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db.dev.lijiabaobei.com.cn:3306/o2_fulfilment?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&useTimezone=true&serverTimezone=GMT%2B8}
#        username: ${SPRING_DATASOURCE_USERNAME:omsdev}
#        password: ${SPRING_DATASOURCE_PASSWORD:omsdev}
#        # 连接池最小空闲连接数
#        minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:10}
#        # 连接池允许的最大连接数
#        maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:90}
#        # 等待连接池分配连接的最大时长（毫秒）
#        connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}
#    props:
#      sql:
#        show: true
#    sharding:
#      tables:
#        ljof_test_sharding:
#          #指定所需分的表
#          actual-data-nodes: data1.ljof_test_sharding$->{0..2}
#          table-strategy:
#            inline:
#              #指定主键
#              sharding-column: shar_id
#              #分表规则为主键除以3取模
#              algorithm-expression: ljof_test_sharding$->{shar_id % 3}
#          key-generator:
#            #指定主键
#            column: shar_id
#            #自定义生成规则
#            type: SNOWFLAKE
##           type: ORDERKEY
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/opsdb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    password:
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .html
    template-loader-path: file:D:/microger/MicroFinance/upload_files/Template/
  thymeleaf:
  #    prefix: file:D:/microger/MicroFinance/upload_files/Template/
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

mybatis:
  configuration:
    #开启驼峰
    map-underscore-to-camel-case: true
    #日志打印sql
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mapper/*.xml
#  check-config-location: true
  type-aliases-package: com.example.demo.**

# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql